### ISSUE TITLE
ok now i see a difference

### ISSUE THREAD

**Issue by SyeGD** [Derpius/gmod-dxr-pbr#1]

**Comment by Derpius** [comment]
Before I close this I assume you're not expecting this to apply to materials in the game world?

These were made for GModDXR and are now primarily used with VisTrace and don't do anything except when used in conjunction with something else.

**Comment by SyeGD** [comment]
> 

I was talking about the example image thingos

**Comment by Derpius** [comment]
Example images were taken with GModDXR
I’ll close this as completed but let me know if you have any issues actually using the textures
